// Code generated by "stringer -type=ActionTD"; DO NOT EDIT.

package omxstate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActTerminate-0]
	_ = x[ActPlaying-1]
	_ = x[ActPause-2]
	_ = x[ActMute-3]
}

const _ActionTD_name = "ActTerminateActPlayingActPauseActMute"

var _ActionTD_index = [...]uint8{0, 12, 22, 30, 37}

func (i ActionTD) String() string {
	if i < 0 || i >= ActionTD(len(_ActionTD_index)-1) {
		return "ActionTD(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionTD_name[_ActionTD_index[i]:_ActionTD_index[i+1]]
}
